spring.application.name=raizes-backend
spring.datasource.url=jdbc:h2:mem:raizesdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jackson.serialization.fail-on-empty-beans=false

# JWT
jwt.secret=XLQ8QVJ5dEj2Or2R2Ir5JXoSLemBiOjbzYsOCvi4lFs
jwt.expiration=3600000

# Logging
logging.level.com.raizes=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs